"""Initialize a standardized research project skeleton.

Cross-platform (Windows / macOS / Linux). Pure stdlib, no third-party deps.
Idempotent: existing files are never overwritten.

The agent is expected to already be inside the project directory. The script
creates core/, experiments/, results/, utils/, docs/ (plus README, .gitignore,
placeholder docs, and optionally a git repo) directly in the target directory.

Usage:
    python init_project.py [--root <target_dir>] [--no-git]
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


_SUBDIRS = ("core", "experiments", "results", "utils", "docs")

_DOCS_PLACEHOLDERS = ("pseudocode.md", "research-notes.md", "bug-fixes.md")

_README = """# {project_name}

## Directory layout

- `core/` — concrete functions / classes (AI decides how to organize).
- `experiments/` — top-level scripts that compose `core/` (single-run scripts, batch runners, config classes).
- `results/` — experiment outputs organized by date, split into `smoke/` and `main/`, one folder per run.
- `utils/` — pure helpers (logger, seeding, etc.).
- `docs/` — pseudocode, bug-fix ledger, research notes. **The agent MUST read every file under `docs/` before each run.** This folder is primarily maintained by the human researcher; the agent only assists.
"""

_GITIGNORE = """# Generated by s01-init
results/
__pycache__/
*.pyc
*.pyo
.venv/
venv/
.env
.DS_Store
Thumbs.db
*.log
.ipynb_checkpoints/
"""


def _write_if_missing(path: Path, content: str) -> bool:
    """Write `content` only if `path` does not exist yet. Returns True if written."""
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _git_init(project_root: Path) -> tuple[bool, str]:
    """Run `git init` if not already a repo. Returns (ran, message)."""
    if (project_root / ".git").is_dir():
        return False, "already a git repository"
    try:
        result = subprocess.run(
            ["git", "init"],
            cwd=str(project_root),
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        return False, "git executable not found on PATH"
    if result.returncode != 0:
        return False, f"git init failed: {result.stderr.strip()}"
    return True, result.stdout.strip()


def init_project(root: Path, *, run_git_init: bool = True) -> dict:
    """Create the project skeleton in `root`. Returns a summary dict."""
    if not root.exists():
        root.mkdir(parents=True, exist_ok=True)

    created_dirs: list[str] = []
    for sub in _SUBDIRS:
        p = root / sub
        if not p.exists():
            p.mkdir(parents=True, exist_ok=True)
            created_dirs.append(sub)

    created_files: list[str] = []
    skipped_files: list[str] = []

    project_name = root.resolve().name
    if _write_if_missing(root / "README.md", _README.format(project_name=project_name)):
        created_files.append("README.md")
    else:
        skipped_files.append("README.md")

    if _write_if_missing(root / ".gitignore", _GITIGNORE):
        created_files.append(".gitignore")
    else:
        skipped_files.append(".gitignore")

    for doc in _DOCS_PLACEHOLDERS:
        rel = f"docs/{doc}"
        if _write_if_missing(root / "docs" / doc, ""):
            created_files.append(rel)
        else:
            skipped_files.append(rel)

    git_info: dict = {"ran": False, "message": "skipped by flag"}
    if run_git_init:
        ran, message = _git_init(root)
        git_info = {"ran": ran, "message": message}

    return {
        "project_root": str(root),
        "created_dirs": created_dirs,
        "created_files": created_files,
        "skipped_files": skipped_files,
        "git": git_info,
    }


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Initialize a standardized research project skeleton "
                    "in the current (or specified) directory.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Target directory in which to create the project layout (default: cwd).",
    )
    parser.add_argument(
        "--no-git",
        action="store_true",
        help="Skip `git init` on the target directory.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        summary = init_project(
            root=args.root,
            run_git_init=not args.no_git,
        )
    except OSError as e:
        print(f"[init_project] ERROR: {e}", file=sys.stderr)
        return 2

    print(f"[init_project] initialized project at {summary['project_root']}")
    if summary["created_dirs"]:
        print(f"[init_project]   dirs created: {', '.join(summary['created_dirs'])}")
    if summary["created_files"]:
        print(f"[init_project]   files created: {', '.join(summary['created_files'])}")
    if summary["skipped_files"]:
        print(f"[init_project]   files skipped (already exist): "
              f"{', '.join(summary['skipped_files'])}")
    print(f"[init_project]   git: {summary['git']['message']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
